### ISSUE TITLE
4-axis shield compatibility

### ISSUE THREAD

**Issue by zapmaker** [LETARTARE/Grbl-xx_with_Arduino#4]
What shields are compatible with Mega 2560 and this version of grbl? Or is there a place to see how to hookup to pins?

**Comment by benouville** [comment]
Bonjour LETARTARE!
Merci pour ce soft, j'ai hâte de l'essayer. Ma question est : puis utiliser ramps1.4 avec ?
merci beaucoup

Can I use ramps 1.4 with this version of grbl? thanks!
