### ISSUE TITLE
Grbl, arduino mega2560 and RAMPS 1.4

### ISSUE THREAD

**Issue by frogmangeek** [LETARTARE/Grbl-xx_with_Arduino#7]
Hi there, 
Was wondering how to use grbl with my RAMPS 1.4 Arduino shield ? 
It would be really cool make this board (originaly for 3d printer )working for milling . 
Best regards .

**Comment by robotabzar** [comment]
Hi ,
I used Grble8c1mega2560 , after upload on ramps 1.4 with arduino 2560 (stepper motor is not connect yet ) I could connect to grblcontrol , the axis move  without problem and I could load nc project as well , but when connect stepper motor , nothing happen , stepper motor does not have anu motion or move , what wrong with that you think ?
